### ISSUE TITLE
Few broken links in docs

### ISSUE THREAD

**Issue by jasongwartz** [sinclairnick/webroute#34]
Huge fan of this design! Looking forward to trying it out for a gradual framework migration.

I've noticed that there are a few broken links in the docs, like here: https://github.com/sinclairnick/webroute/blob/a96ab9b9d3a710015f4ea8e84188f47cc3e0fa34/docs/content/docs/route/guides/building-apps.mdx?plain=1#L16 Perhaps there's been a docs refactor recently?

**Comment by sinclairnick** [comment]
Hey @jasongwartz thanks for pointing this out!

I'd suspected there might be a broken link or two.

I'm actually in the process of overhauling the docs to make everything easier to understand. The current docs are ok, but a little chaotic. So I'll certainly fix all the links during this update, which should hopefully roll out within the next week or so.

Thanks
