### ISSUE TITLE
Route output validation not checked when returning Response

### ISSUE THREAD

**Issue by jasongwartz** [sinclairnick/webroute#35]
The following route fails validation as expected (and also has a typecheck error from inference, nice touch!):
```
export const GET = route()
  .output(z.literal(true))
  .handle(() => {
    return false;
  });
```

However the following example does not fail validation, but returns `false` with HTTP status 200:
```
export const GET = route()
  .output(z.literal(true))
  .handle(() => {
    return Response.json(false);
  });
```
I can see that it's because of the conditional here: https://github.com/sinclairnick/webroute/blob/main/packages/route/src/route/handler/index.ts#L161-L175 so perhaps it's intentional behaviour? If so, it would be good to document.

I can see why it might not be easy to implement - reading and parsing the JSON body doesn't seem ideal, and I'm not sure it's possible to extract the originally-submitted JS object from a `Response` that was constructed with `Response.json()`.

**Comment by sinclairnick** [comment]
Nice catch!

Yeah I agree with your points, and I had decided that the least opinionated approach would be to just skip any validation if `Response` was returned, to avoid any unnecessary overhead.

And of course this SHOULD be clearly documented - as it is one of the few behaviours that aren't entirely intuitive. I'll make sure to document this much more clearly.

Thanks for pointing this out - a very fair and important point

**Comment by sinclairnick** [comment]
Have created an issue #32
